# mk/07_secrets.mk
# ============================================================================
# Secret Management: SOPS/Age Decryption Orchestration
# RAM-only, no decrypted files on disk
# ============================================================================

# ------------------------------------------------------------
# Guard: ensure mk/config.mk has been loaded
# ------------------------------------------------------------

REQUIRED_SECRETS_VARS := \
	SOPS_BIN \
	SECRETS_FILE \
	SOPS_AGE_KEY_FILE \
	SOPS_AGE_KEY_DIR \
	SOPS_AGE_PUBKEY_EXPECTED \
	ROOT_UID \
	ROOT_GID \
	USER \
	HOMELAB_RUNTIME_USER \
	SECRETS_TMP_DIR \
	YQ \
	ROUTER_ADDR

REQUIRED_SECRET_VARS := \
	SOPS_BIN \
	SECRETS_FILE \
	YQ

secrets-vars-check:
	@for v in $(REQUIRED_SECRETS_VARS); do \
		if [ -z "$${v}" ]; then \
			echo "❌ Variable $$v is not defined — check mk/config.mk"; \
			exit 1; \
		fi; \
	done

secret-vars-check:
	@for v in $(REQUIRED_SECRET_VARS); do \
		if [ -z "$${v}" ]; then \
			echo "❌ Variable $$v is not defined — check mk/config.mk"; \
			exit 1; \
		fi; \
	done

SECRETS_TARGETS := \
	ops-init \
	secrets-status \
	secrets-break-lock \
	secrets-dump \
	secrets-export \
	secrets-verify \
	secrets-edit \
	secrets-ready \
	secrets-init \
	check-age-key \
	secrets-runtime-init \
	ddns-env \
	ddns-runtime \
	test-infomaniak-token \
	test-infomaniak-txt-dryrun \
	compute-stamp-salt

$(SECRETS_TARGETS): secrets-vars-check

# ----------------------------------------------------------------------------
# 0. RAM-only workspace (per-user)
# ----------------------------------------------------------------------------

HOMELAB_RUNTIME_BASE := /run/user/$(USER_UID)/homelab
HOMELAB_RUNTIME_USER := $(HOMELAB_RUNTIME_BASE)

# Per-user secrets tmp dir (RAM-only)
export SECRETS_TMP_DIR := $(HOMELAB_RUNTIME_USER)/secrets/tmp

export SECRETS_LOCK := $(HOMELAB_RUNTIME_USER)/secrets/lock
export SECRETS_LOCK_PID := $(SECRETS_LOCK)/pid
export SECRETS_LOCK_TS  := $(SECRETS_LOCK)/ts

# Lock expires after N seconds
SECRETS_LOCK_MAX_AGE := 30

# Call as: $(call WITH_SECRETS, <shell commands>)
# Secrets are scoped to a subshell - they do NOT leak into the parent recipe
# environment or subsequent make recipe lines.
# --------------------------------------------------------------------
# WITH_SECRETS — execute commands with decrypted secrets exported to environment
# --------------------------------------------------------------------
define WITH_SECRETS
( \
	[ -n "$$SOPS_BIN" ] && [ -n "$$YQ" ] || { echo "❌ SOPS_BIN or YQ not set"; exit 1; }; \
	SECS="$$($$SOPS_BIN -d "$(SECRETS_FILE)" | $$YQ -r '.. | select(tag == "!!str" or tag == "!!int" or tag == "!!bool") | (path | join("_")) + "=" + .')"; \
	if [ -n "$$SECS" ]; then export $$SECS; fi; \
	$(1) \
)
endef

define SECRET
$(SOPS_BIN) -d "$(SECRETS_FILE)" | $(YQ) -r ".$(1)"
endef

# ----------------------------------------------------------------------------
# DHCP static lease aggregation (non-secret, derived from secrets)
# ----------------------------------------------------------------------------
define LOAD_STATIC_DHCP
STATIC_DHCP="$$( $(call WITH_SECRETS, sh -c 'for v in $$(compgen -A variable | grep "^dhcp_static_"); do printf "%s " "$${!v}"; done') )"; export STATIC_DHCP
endef

# ----------------------------------------------------------------------------
# 1. SOPS CONFIGURATION & GUARDS
# ----------------------------------------------------------------------------

.PHONY: sops-init
sops-init:
	@set -euo pipefail; \
	tmp="$$(mktemp)"; \
	{ \
		echo "# .sops.yaml (generated by sops-init)"; \
		echo "creation_rules:"; \
		echo "  - path_regex: .*/secrets\\.enc\\.yaml$$"; \
		echo "    age: $(SOPS_AGE_PUBKEY_EXPECTED)"; \
		echo "format: yaml"; \
	} > "$$tmp"; \
	if ! cmp --silent "$$tmp" "$(REPO_ROOT)/.sops.yaml" 2>/dev/null; then \
		echo "⚙️ Updating $(REPO_ROOT)/.sops.yaml"; \
		mv "$$tmp" "$(REPO_ROOT)/.sops.yaml"; \
	else \
		[ -z "$(VERBOSE)" ] || [ "$(VERBOSE)" = "0" ] || echo "🟢 $(REPO_ROOT)/.sops.yaml already up-to-date"; \
		rm "$$tmp"; \
	fi

.PHONY: secrets-status
secrets-status:
	@set -euo pipefail; \
	echo "🔍 Secrets subsystem status"; \
	echo "  USER: $$(id -un)"; \
	echo "  FILE: $(SECRETS_FILE)"; \
	echo "  BASE: $(HOMELAB_RUNTIME_USER)/secrets"; \
	echo ""; \
	if [ -d "$(SECRETS_LOCK)" ]; then \
		echo "Lock state: 🔒 LOCKED"; \
		[ -f "$(SECRETS_LOCK_PID)" ] && echo "  PID ➡️ $$(cat "$(SECRETS_LOCK_PID)")"; \
		[ -f "$(SECRETS_LOCK_TS)" ] && echo "  TS  ➡️ $$(cat "$(SECRETS_LOCK_TS)")"; \
	else \
		echo "Lock state: 🔓 UNLOCKED"; \
	fi

.PHONY: secrets-break-lock
secrets-break-lock:
	@set -euo pipefail; \
	if [ ! -d "$(SECRETS_LOCK)" ]; then \
		echo "🔓 No lock present"; \
		exit 0; \
	fi; \
	echo "⚠️ Manual lock override requested"; \
	[ -f "$(SECRETS_LOCK_PID)" ] && echo "  Locked by PID: $$(cat "$(SECRETS_LOCK_PID)")"; \
	[ -f "$(SECRETS_LOCK_TS)" ] && echo "  Lock timestamp: $$(cat "$(SECRETS_LOCK_TS)")"; \
	rm -rf "$(SECRETS_LOCK)"; \
	echo "🔓 Lock removed (forced unlock)"

.PHONY: secrets-dump
secrets-dump:
	@set -euo pipefail; \
	if [ ! -f "$(SECRETS_FILE)" ]; then \
		echo "❌ Secrets file not found: $(SECRETS_FILE)"; \
		echo "👉 To restore secrets:"; \
		echo "   1. Retrieve the encrypted backup attachment from your KeePass secure database."; \
		echo "   2. Save it locally to: $(SECRETS_FILE)"; \
		echo "   3. Decrypt or edit using: sops $(SECRETS_FILE)"; \
		exit 1; \
	fi; \
	echo "⚠️  WARNING: You are about to display plaintext secrets on the terminal!"; \
	echo "🔐 Dumping full decrypted secrets (including comments for password manager):"; \
	echo "--------------------------------------------------------------------------------"; \
	$(SOPS_BIN) -d "$(SECRETS_FILE)"; \
	echo "--------------------------------------------------------------------------------"; \
	echo "💡 Tip: Run 'clear' now to wipe your terminal history of sensitive values."

.PHONY: secrets-export
secrets-export:
	@set -euo pipefail; \
	if [ ! -f "$(SECRETS_FILE)" ]; then \
		echo "❌ Secrets file not found: $(SECRETS_FILE)"; \
		echo "👉 To restore secrets:"; \
		echo "   1. Retrieve the encrypted backup attachment from your KeePass secure database."; \
		echo "   2. Save it locally to: $(SECRETS_FILE)"; \
		echo "   3. Decrypt or edit using: sops $(SECRETS_FILE)"; \
		exit 1; \
	fi; \
	echo "⚠️  WARNING: Exporting plaintext secrets to standard output!"; \
	echo "🔐 Exporting decrypted secrets as environment variables:"; \
	$(SOPS_BIN) -d "$(SECRETS_FILE)" \
		| $(YQ) -r '.. | select(tag == "!!str" or tag == "!!int" or tag == "!!bool") | (path | join("_")) + "=" + .'; \
	echo "💡 Tip: Run 'clear' now to wipe your terminal history of sensitive values."

.PHONY: secrets-verify
secrets-verify: $(YQ_STAMP)
	@echo "🔍 Verifying secrets integrity"

	@echo "  • Checking encrypted file exists..."
	@if [ ! -f "$(SECRETS_FILE)" ]; then \
		echo "❌ Missing: $(SECRETS_FILE)"; \
		echo "➡️ To initialize a new encrypted secrets file:"; \
		echo "   SOPS_AGE_KEY_FILE=$(SOPS_AGE_KEY_FILE) $(SOPS_BIN) $(SECRETS_FILE)"; \
		exit 1; \
	fi

	@echo "  • Checking SOPS identity contract..."
	@if ! grep -Fq "$(SOPS_AGE_PUBKEY_EXPECTED)" .sops.yaml; then \
		echo "❌ .sops.yaml does not contain expected Age public key"; \
		exit 1; \
	fi

	@echo "  • Checking SOPS decryption..."
	@$(SOPS_BIN) -d "$(SECRETS_FILE)" >/dev/null || { echo "❌ Decryption failed"; exit 1; }

	@echo "  • Checking YAML structure..."
	@$(SOPS_BIN) -d "$(SECRETS_FILE)" \
		| $(YQ) e 'keys' - >/dev/null || { echo "❌ Invalid YAML"; exit 1; }

	@echo "  • Checking encryption identity..."
	@$(SOPS_BIN) -d "$(SECRETS_FILE)" \
		| $(YQ) e '.sops.age[].recipient' - \
		| grep -Fq "$(SOPS_AGE_PUBKEY_EXPECTED)" \
		|| { echo "❌ Secrets not encrypted with expected Age key"; exit 1; }

	@echo "🟢 Secrets OK — decryptable, structurally valid, correct identity"

.PHONY: secrets-edit
secrets-edit:
	@{ \
		lock_dir="$(SECRETS_LOCK)"; \
		lock_ts="$(SECRETS_LOCK_TS)"; \
		now=$$(date +%s); \
		# Stale lock handling \
		if [ -d "$$lock_dir" ]; then \
			if [ -f "$$lock_ts" ]; then \
				ts=$$(cat "$$lock_ts" 2>/dev/null || echo 0); \
				age=$$((now - ts)); \
				if [ $$age -gt $(SECRETS_LOCK_MAX_AGE) ]; then \
					echo "⚠️ Stale secrets lock detected (age $$age s > $(SEcrets_LOCK_MAX_AGE)s). Breaking it."; \
					rm -rf "$$lock_dir"; \
				fi; \
			else \
				echo "⚠️ Lock directory exists but no timestamp — breaking lock."; \
				rm -rf "$$lock_dir"; \
			fi; \
		fi; \
		# Acquire lock \
		while ! mkdir "$$lock_dir" 2>/dev/null; do \
			echo "⏳ Waiting for secrets lock (use make secrets-break-lock to force-remove the lock) ..."; \
			sleep 0.1; \
		done; \
		echo $$now > "$$lock_ts"; \
		trap 'rm -rf "$$lock_dir" 2>/dev/null || true' EXIT; \
		echo "📝 Editing encrypted secrets with SOPS ($(SECRETS_FILE))"; \
		status=0; \
		TMPDIR="$(SECRETS_TMP_DIR)" $(SOPS_BIN) "$(SECRETS_FILE)" || status=$$?; \
		if [ $$status -eq 200 ]; then \
			status=0; \
		fi; \
		if [ $$status -ne 0 ]; then \
			echo "❌ SOPS error (exit $$status)"; \
			exit $$status; \
		fi; \
		true; \
	}

secrets-ready: $(STAMP_SOPS)
	@if [ ! -f "$(SECRETS_FILE)" ]; then \
		echo "Error: cannot operate on non-existent file \"$(SECRETS_FILE)\""; \
		echo "➡️ Initialize or restore your encrypted secrets file at $(SECRETS_FILE)"; \
		exit 1; \
	fi; \
	if ! $(SOPS_BIN) -d "$(SECRETS_FILE)" >/dev/null; then \
		echo "❌ Failed to decrypt $(SECRETS_FILE)"; \
		exit 1; \
	fi; \
	[ -z "$(VERBOSE)" ] || [ "$(VERBOSE)" = "0" ] || echo "🟢 Secrets OK"

.PHONY: secrets-init
secrets-init:
	@set -euo pipefail; \
	echo "🔐 Initializing fresh encrypted secrets file: $(SECRETS_FILE)"; \
	if [ -f "$(SECRETS_FILE)" ]; then \
		echo "⚠️ $(SECRETS_FILE) already exists — refusing to overwrite"; \
		exit 1; \
	fi; \
	echo "⚙️ Creating empty secrets structure"; \
	printf "%s\n" \
		"infomaniak_api_key: \"\"" \
		"infomaniak_api_secret: \"\"" \
		"infomaniak_api_token: \"\"" \
		"ddns_username: \"\"" \
		"ddns_password: \"\"" \
		"ddns_topdomain: \"\"" \
		"router_addr: \"$(ROUTER_ADDR)\"" \
		> "$(SECRETS_FILE).tmp"; \
	echo "🔐 Encrypting with SOPS (Age key: $(SOPS_AGE_PUBKEY))"; \
	TMPDIR="$(SECRETS_TMP_DIR)" \
		$(SOPS_BIN) --encrypt --age "$(SOPS_AGE_PUBKEY)" \
		"$(SECRETS_FILE).tmp" > "$(SECRETS_FILE)"; \
	rm -f "$(SECRETS_FILE).tmp"; \
	echo "🟢 secrets.enc.yaml created and encrypted"

.PHONY: check-age-key
check-age-key:
	@echo "🔍 Checking system AGE key (/etc/sops/keys/age.key)"

	@{ \
		key="/etc/sops/keys/age.key"; \
		if [ ! -f "$$key" ]; then \
			echo "❌ AGE key missing at $$key"; \
			exit 1; \
		fi; \
		info="$$(stat -c '%a %U %G' "$$key" 2>/dev/null || echo MISSING)"; \
		if [ "$$info" != "640 root admin" ]; then \
			echo "⚠️  AGE key permissions drifted ($$info ➡️ fixing)"; \
			$(run_as_root) sh -c "chown root:admin \"$$key\" && chmod 640 \"$$key\""; \
			info="$$(stat -c '%a %U %G' "$$key")"; \
			echo "🛠️  Permissions set to $$info"; \
		fi; \
	}

	@if ! sudo -E -u "$(USER)" sops -d "$(SECRETS_FILE)" >/dev/null 2>&1; then \
		echo "❌ AGE key exists but cannot decrypt $(SECRETS_FILE) as $(USER)"; \
		exit 1; \
	fi

	@{ \
		pub="$$( $(run_as_root) age-keygen -y /etc/sops/keys/age.key 2>/dev/null )"; \
		if [ -z "$$pub" ]; then \
			echo "❌ AGE key is invalid or unreadable"; \
			exit 1; \
		fi; \
		echo "🟢 AGE key OK — ts=$$(stat -c '%y' /etc/sops/keys/age.key) pub=$$pub user=$(USER)"; \
	}

# Ensure per-user runtime secrets workspace exists (RAM-only, managed by systemd)
.PHONY: secrets-runtime-init
secrets-runtime-init:
	@mkdir -p \
		"$(HOMELAB_RUNTIME_USER)/secrets" \
		"$(SECRETS_TMP_DIR)" \
		"$(HOMELAB_RUNTIME_USER)/ddns"

DDNS_ENV_FILE := /etc/homelab/ddns.env

.PHONY: ddns-env-dir
ddns-env-dir:
	@$(run_as_root) install -d -m 0755 -o $(ROOT_UID) -g $(ROOT_GID) /etc/homelab

.PHONY: ddns-env
ddns-env: ddns-env-dir secrets-runtime-init $(YQ_STAMP)
	@{ \
		export SOPS_BIN="$(SOPS_BIN)"; \
		export SECRETS_FILE="$(SECRETS_FILE)"; \
		export YQ="$(YQ)"; \
		\
		$(run_as_root) bash -euo pipefail -c ' \
			SOPS_BIN="$${SOPS_BIN:-/usr/local/bin/sops}"; \
			SECRETS_FILE="$${SECRETS_FILE:-/tank/julie/src/homelab/secrets.enc.yaml}"; \
			YQ="$${YQ:-/usr/local/bin/yq}"; \
			tmp="$$(mktemp)"; \
			trap "rm -f \"$$tmp\"" EXIT; \
			umask 077; \
			\
			eval "$$( \
				"$$SOPS_BIN" -d "$$SECRETS_FILE" \
				| "$$YQ" -r '\'' \
					"INFOMANIAK_API_KEY=" + .infomaniak_api_key, \
					"INFOMANIAK_API_SECRET=" + .infomaniak_api_secret \
				'\'' \
			)"; \
			\
			printf "%s\n" \
				"INFOMANIAK_API_KEY=$$INFOMANIAK_API_KEY" \
				"INFOMANIAK_API_SECRET=$$INFOMANIAK_API_SECRET" \
				> "$$tmp"; \
			\
			install -m 600 -o $(ROOT_UID) -g $(ROOT_GID) "$$tmp" "$(DDNS_ENV_FILE)"; \
		'; \
		if [ "$(VERBOSE)" -ge 1 ]; then echo "🔐 Updated $(DDNS_ENV_FILE)"; fi; \
	}

DDNS_RUNTIME_FILE := $(HOMELAB_RUNTIME_USER)/ddns/ddns.conf
# Contract: root-owned, RAM-only, consumed by DDNS updater

.PHONY: ddns-runtime
ddns-runtime: $(YQ_STAMP) secrets-runtime-init
	@{ \
		export SOPS_BIN="$(SOPS_BIN)"; \
		export SECRETS_FILE="$(SECRETS_FILE)"; \
		export YQ="$(YQ)"; \
		\
		$(run_as_root) bash -euo pipefail -c '\
			tmp="$$(mktemp)"; \
			trap "rm -f \"$$tmp\"" EXIT; \
			umask 077; \
			\
			eval "$$( \
				"$$SOPS_BIN" -d "$$SECRETS_FILE" \
				| "$$YQ" -r '\'' \
					"ddns_username=\(.ddns_username)", \
					"ddns_password=\(.ddns_password)", \
					"ddns_topdomain=\(.ddns_topdomain)" \
				'\'' \
			)"; \
			\
			printf "%s\n" \
				"ddns_username=$$ddns_username" \
				"ddns_password=$$ddns_password" \
				"ddns_topdomain=$$ddns_topdomain" \
				> "$$tmp"; \
			\
			install -m 600 -o $(ROOT_UID) -g $(ROOT_GID) "$$tmp" "$(DDNS_RUNTIME_FILE)"; \
		'; \
		echo "🔐 DDNS runtime file updated: $(DDNS_RUNTIME_FILE)"; \
	}

.PHONY: test-infomaniak-token
test-infomaniak-token: $(STAMP_SOPS)
	@$(call WITH_SECRETS, printf "INFOMANIAK_API_TOKEN=%s\n" "$$INFOMANIAK_API_TOKEN")

.PHONY: test-infomaniak-dns-api
test-infomaniak-dns-api: $(STAMP_SOPS)
	@$(call WITH_SECRETS, \
		curl -s -o /dev/null -w "HTTP=%{http_code}\n" \
			-H "Authorization: Bearer $$INFOMANIAK_API_TOKEN" \
			https://api.infomaniak.com/2/domains/domains \
	)

.PHONY: test-infomaniak-txt-dryrun
test-infomaniak-txt-dryrun: $(STAMP_SOPS)
	@$(call WITH_SECRETS, \
		if [ -z "$${ddns_topdomain:-}" ]; then \
			echo "❌ Error: ddns_topdomain is not defined in secrets"; \
			exit 1; \
		fi; \
		domain="$$ddns_topdomain"; \
		name="_acme-challenge.dryrun"; \
		value="homelab-dryrun-$$RANDOM"; \
		echo "🟦 Creating TXT on zone $$domain: $$name ➡️ $$value"; \
		resp=$$(curl -s -X POST \
			-H "Authorization: Bearer $$INFOMANIAK_API_TOKEN" \
			-H "Content-Type: application/json" \
			-d "{\"type\":\"TXT\",\"name\":\"$$name\",\"target\":\"$$value\",\"ttl\":60}" \
			"https://api.infomaniak.com/2/zones/$$domain/records"); \
		echo "$$resp" | grep -q '"id"' || { echo "❌ TXT create failed"; echo "$$resp"; exit 1; }; \
		rec_id=$$(echo "$$resp" | sed -n 's/.*\"id\":[ ]*\([0-9]*\).*/\1/p'); \
		echo "🟢 Created TXT record id=$$rec_id"; \
		echo "🟦 Deleting TXT id=$$rec_id"; \
		curl -s -X DELETE \
			-H "Authorization: Bearer $$INFOMANIAK_API_TOKEN" \
			"https://api.infomaniak.com/2/zones/$$domain/records/$$rec_id" >/dev/null; \
		echo "🟢 Deleted TXT record"; \
	)

.PHONY: compute-stamp-salt
compute-stamp-salt:
	@install -d -o "$(ROOT_UID)" -g "$(ROOT_GID)" -m 700 /run/user/$(ROOT_UID)/homelab
	@STAMP_SALT="$$(sha256sum "$(SOPS_AGE_KEY_FILE)" | awk '{print $$1}')"; \
		echo "export STAMP_SALT=$$STAMP_SALT" > /run/user/$(ROOT_UID)/homelab/stamp_salt.env
	@echo "🔐 STAMP_SALT computed and stored in /run/user/$(ROOT_UID)/homelab/stamp_salt.env"