# mk/router/40_firewall.mk
# ------------------------------------------------------------
# FIREWALL INVARIANTS
# ------------------------------------------------------------

.PHONY: router-firewall-hardened
router-firewall-hardened: | router-ssh-check
	@echo "🛡️ Validating router firewall invariants"
	@$(call WITH_SECRETS, \
		ssh -p "$$ROUTER_SSH_PORT" "$$SSH_USER_ROUTER@$$ROUTER_ADDR" '\
			set -e; \
			if [ ! -x /jffs/scripts/firewall-start ]; then \
				echo "❌ Missing /jffs/scripts/firewall-start"; exit 1; \
			fi; \
			echo "🟢 firewall-start present"; \
		' \
	)
	@echo "🛡️ Router firewall hardened"

define ROUTER_NAT_SYNOLOGY
# 5. Synology WebDAV (5006)
iptables -t nat -A HOMELAB_NAT -p tcp --dport 5006 -j DNAT --to-destination $(LAN_SYNOLOGY):5006
iptables -A HOMELAB_FWD -p tcp -d $(LAN_SYNOLOGY) --dport 5006 -j ACCEPT

# 6. Synology Drive (6690)
iptables -t nat -A HOMELAB_NAT -p tcp --dport 6690 -j DNAT --to-destination $(LAN_SYNOLOGY):6690
iptables -A HOMELAB_FWD -p tcp -d $(LAN_SYNOLOGY) --dport 6690 -j ACCEPT
endef

# Base NAT script body — WG rules appended dynamically from wg-interfaces.tsv
define ROUTER_NAT_SCRIPT
#!/bin/sh
# NAT & port-forwarding rules — Auto-generated by homelab
# DO NOT EDIT MANUALLY. Generated by recipe router-nat-install.
# homelab-nat-version: $(shell git rev-parse HEAD)

# 1. Ensure dedicated chains exist
iptables -t nat -N HOMELAB_NAT 2>/dev/null || true
iptables -N HOMELAB_FWD 2>/dev/null || true
iptables -N HOMELAB_INPUT 2>/dev/null || true

# 2. Flush homelab-managed chains
iptables -t nat -F HOMELAB_NAT
iptables -F HOMELAB_FWD
iptables -F HOMELAB_INPUT

# 3. Hook chains into persistent Merlin structural vectors
iptables -t nat -D VSERVER -j HOMELAB_NAT 2>/dev/null || true
iptables -t nat -I VSERVER 1 -j HOMELAB_NAT
iptables -D FORWARD -j HOMELAB_FWD 2>/dev/null || true
iptables -I FORWARD 1 -j HOMELAB_FWD
iptables -D INPUT -j HOMELAB_INPUT 2>/dev/null || true
iptables -I INPUT 1 -j HOMELAB_INPUT

# 4. Caddy HTTP/HTTPS (router-local)
iptables -A HOMELAB_INPUT -p tcp --dport 80  -j ACCEPT
iptables -A HOMELAB_INPUT -p tcp --dport 443 -j ACCEPT

$(if $(LAN_SYNOLOGY),$(ROUTER_NAT_SYNOLOGY))
endef

# Out-of-repo absolute path for topology isolation
WG_INTERFACES_TSV := /volume1/homelab/wireguard/input/wg-interfaces.tsv

# NOTE: $(WG_INTERFACES_TSV) is NOT a Make prerequisite.
# Because it lives under /volume1/... on the NAS, Make would treat it as a
# real file dependency and abort on non‑NAS hosts with:
#      *** No rule to make target '/volume1/...'. Stop.
# We therefore check its existence at runtime instead of wiring it into the DAG.
.PHONY: router-nat-install
router-nat-install: router-install-scripts
	@echo "🔧 Rendering and deploying NAT rules"
	@if [ ! -f "$(WG_INTERFACES_TSV)" ]; then \
		echo "❌ Topology file missing at $(WG_INTERFACES_TSV)"; exit 1; \
	fi

	# 0a) Validate TSV header contract
	@awk -F'\t' 'NR==1 { \
		if ($$1!="iface" || $$2!="host_id" || $$3!="listen_port" || $$7!="enabled") { \
			print "❌ wg-interfaces.tsv: unexpected column layout"; \
			print "   expected: iface, host_id, listen_port, ..., enabled"; \
			exit 1; \
		} \
	}' "$(WG_INTERFACES_TSV)"

	# 0b) Validate all rows (syntax, semantics, collisions)
	@awk -F'\t' -v lan_nas="$(LAN_NAS)" -v r_ssh="$$ROUTER_SSH_PORT" ' \
		BEGIN { \
			synology_ports["5006"]=1; \
			synology_ports["6690"]=1; \
			caddy_ports["80"]=1; \
			caddy_ports["443"]=1; \
			merlin_ports["8080"]=1; \
			merlin_ports["8443"]=1; \
			if (r_ssh != "") merlin_ports[r_ssh]=1; \
		} \
		NR==1 { next } \
		$$0 ~ /^[[:space:]]*$$/ { next } \
		$$0 ~ /^#/ { next } \
		NF < 7 { \
			printf "❌ Invalid row (expected ≥7 columns): %s\n", $$0; \
			exit 1; \
		} \
		{ \
			iface=$$1; host=$$2; port=$$3; enabled=$$7; \
			# iface validation (always applies) \
			if (iface !~ /^(wg[0-9]+|wgs[0-9])$$/) { \
				printf "❌ Invalid iface name '\''%s'\'' (expected wgN|wgsN)\n", iface; \
				exit 1; \
			} \
			if (seen_iface[iface]++) { \
				printf "❌ Duplicate iface '\''%s'\''\n", iface; \
				exit 1; \
			} \
			# host_id validation (always applies) \
			if (host!="router" && host!="nas") { \
				printf "❌ Invalid host_id '\''%s'\'' (expected router|nas)\n", host; \
				exit 1; \
			} \
			# enabled flag validation (always applies) \
			if (enabled!="0" && enabled!="1") { \
				printf "❌ Invalid enabled flag '\''%s'\'' (expected 0|1)\n", enabled; \
				exit 1; \
			} \
			# STOP HERE if disabled \
			if (enabled == "0") next; \
			# From here on, only enabled rows are validated \
			if (port !~ /^[0-9]+$$/) { \
				printf "❌ Invalid listen_port '\''%s'\'' (not numeric)\n", port; \
				exit 1; \
			} \
			if (port < 1 || port > 65535) { \
				printf "❌ Invalid listen_port '\''%s'\'' (out of range)\n", port; \
				exit 1; \
			} \
			if (host=="nas" && lan_nas=="") { \
				printf "❌ host_id=nas but LAN_NAS is not defined\n"; \
				exit 1; \
			} \
			if (seen_port[port] != "") { \
				printf "❌ Duplicate listen_port %s used by interfaces: %s and %s\n", port, seen_port[port], iface; \
				exit 1; \
			} \
			seen_port[port] = iface; \
			if (port in synology_ports) { \
				printf "❌ listen_port %s conflicts with Synology service port\n", port; \
				exit 1; \
			} \
			if (port in caddy_ports) { \
				printf "❌ listen_port %s conflicts with Caddy HTTP/HTTPS\n", port; \
				exit 1; \
			} \
			if (port in merlin_ports) { \
				printf "❌ listen_port %s conflicts with core Router SSH/UI service port\n", port; \
				exit 1; \
			} \
		} \
	' "$(WG_INTERFACES_TSV)"

	# 1) Write base script via native Make I/O
	$(file >$(TMP_ROUTER_NAT),$(ROUTER_NAT_SCRIPT))

	# 2) Append WG-derived NAT rules safely isolating shell scope variables
	@awk -F'\t' -v lan_nas="$(LAN_NAS)" '\
		NR==1 { next } \
		$$0 ~ /^#/ { next } \
		$$0 ~ /^[[:space:]]*$$/ { next } \
		NF < 7 { next } \
		{ \
			enabled = $$7; \
			port    = $$3; \
			host    = $$2; \
			if (enabled != "1") next; \
			if (port == "0")    next; \
			if (host == "nas") {
				# WAN → NAS:wgX_port (allowed)
				printf "iptables -t nat -A HOMELAB_NAT -p udp --dport %s -j DNAT --to-destination %s:%s\n", port, lan_nas, port;
				printf "iptables -A HOMELAB_FWD -p udp -d %s --dport %s -j ACCEPT\n", lan_nas, port;

				# LAN → NAS:wgX_port (REJECT — hairpin protection) -> LAN clients will fail fast instead of black‑holing traffic in a loop
				printf "iptables -A HOMELAB_FWD -s 10.89.12.0/24 -d %s -p udp --dport %s -j REJECT\n", lan_nas, port;
			}
			else if (host == "router") { \
				printf "iptables -A HOMELAB_INPUT -p udp --dport %s -j ACCEPT\n", port; \
			} \
		} \
	' "$(WG_INTERFACES_TSV)" >> "$(TMP_ROUTER_NAT)"

	# 3) Execute synchronization pipeline wrapping cleanup actions into immediate continuation
	@{ \
		rc=0; \
		$(call PUSH_ROUTER_SCRIPT,"$(TMP_ROUTER_NAT)","$(ROUTER_SCRIPTS)/nat-start"); \
		rc=$$?; \
		if [ $$rc -ne 0 ] && [ $$rc -ne 3 ]; then exit $$rc; fi; \
		echo "🟢 NAT rules deployed to router and verified"
	}

define ROUTER_NAT_DUMP_SCRIPT
set -e

printf "\n=== [ VSERVER HOOK INVARIANT ] ===\n"
if iptables -t nat -L VSERVER -n --line-numbers \
	| sed '1,2d' \
	| grep -q 'HOMELAB_NAT'; then
	echo "🟢 HOMELAB_NAT is correctly hooked into VSERVER"
else
	echo "❌ HOMELAB_NAT is NOT hooked into VSERVER"
fi

printf "\n=== [ HOMELAB_NAT (DNAT / Port Forwards) ] ===\n"
if iptables -t nat -S HOMELAB_NAT >/dev/null 2>&1; then
	if ! iptables -t nat -L HOMELAB_NAT -n --line-numbers | sed 1,2d | grep .; then
		echo "  (Chain is empty)"
	fi
else
	echo "❌ Chain HOMELAB_NAT does not exist"
fi

printf "\n=== [ HOMELAB_INPUT (Router-local UDP Accept) ] ===\n"
if iptables -S HOMELAB_INPUT >/dev/null 2>&1; then
	if ! iptables -L HOMELAB_INPUT -n --line-numbers | sed 1,2d | grep .; then
		echo "  (Chain is empty)"
	fi
else
	echo "❌ Chain HOMELAB_INPUT does not exist"
fi

printf "\n=== [ HOMELAB_FWD (Forwarding Permissions) ] ===\n"
if iptables -S HOMELAB_FWD >/dev/null 2>&1; then
	if ! iptables -L HOMELAB_FWD -n --line-numbers | sed 1,2d | grep .; then
		echo "  (Chain is empty)"
	fi
else
	echo "❌ Chain HOMELAB_FWD does not exist"
fi

printf "\n📦 NAT dump complete.\n\n"
endef

.PHONY: router-nat-dump
router-nat-dump: | router-ssh-check
	@echo "📊 Querying active homelab firewall configurations on router..."
	$(file >$(TMP_ROUTER_NAT).dump,$(ROUTER_NAT_DUMP_SCRIPT))
	@$(call WITH_SECRETS, sh -c '\
		ssh -p "$$ROUTER_SSH_PORT" "$$SSH_USER_ROUTER@$$ROUTER_ADDR" "cat > /tmp/nat-dump.sh" < "$(TMP_ROUTER_NAT).dump"; \
		ssh -p "$$ROUTER_SSH_PORT" "$$SSH_USER_ROUTER@$$ROUTER_ADDR" "sh /tmp/nat-dump.sh && rm -f /tmp/nat-dump.sh"; \
		rm -f "$(TMP_ROUTER_NAT).dump" \
	')


.PHONY: router-firewall-started
router-firewall-started: | router-install-scripts router-nat-install
	@echo "🔁 Reloading router firewall (firewall-start)"
	@ssh -p $(ROUTER_SSH_PORT) $(ROUTER_HOST) "sh /jffs/scripts/firewall-start"
	@echo "🟢 Router firewall reloaded"

.PHONY: router
router: router-all

.PHONY: router-all
router-all: sanity router-bootstrap router-converge router-verify \
			router-install-scripts \
			router-dnsmasq-conf \
			router-nat-install \
			router-firewall-started
	@echo "🎯 Router bootstrap + converge + verify complete"

router-configure:
	@$(call WITH_SECRETS, \
		echo "Task 1: Pinging $$ROUTER_ADDR..."; \
		sudo -E ping -c1 "$$ROUTER_ADDR"; \
		echo "Task 2: Checking service on $$ROUTER_ADDR..."; \
		sudo -E curl -I "http://$$ROUTER_ADDR"; \
		echo "All tasks complete."; \
	)

.PHONY: router-nat-apply
router-nat-apply: | router-install-scripts router-nat-install router-firewall-started
	@echo "🚀 Applying NAT pipeline (deploy + activate + verify)"

	# 1) Generate dump script locally (atomic)
	$(file >$(TMP_ROUTER_NAT).dump,$(ROUTER_NAT_DUMP_SCRIPT))

	# 2) Upload atomically to router as root
	@$(call WITH_SECRETS, sh -c '\
		ssh -p "$$ROUTER_SSH_PORT" "$$SSH_USER_ROUTER@$$ROUTER_ADDR" "\
			umask 077; \
			cat > /tmp/nat-dump.sh.tmp; \
			mv /tmp/nat-dump.sh.tmp /tmp/nat-dump.sh \
		" < "$(TMP_ROUTER_NAT).dump"; \
		rm -f "$(TMP_ROUTER_NAT).dump" \
	')

	# 3) Validate ownership + permissions before execution
	@$(call WITH_SECRETS, sh -c '\
		ssh -p "$$ROUTER_SSH_PORT" "$$SSH_USER_ROUTER@$$ROUTER_ADDR" "\
			set -e; \
			[ -f /tmp/nat-dump.sh ] || { echo \"❌ nat-dump.sh missing\"; exit 1; }; \
			\
			# Ownership check (BusyBox-safe): compare owner name via ls -l \
			owner=\$$(ls -l /tmp/nat-dump.sh | awk \"{print \\\$3}\"); \
			[ \"\$$owner\" = \"root\" ] || { echo \"❌ nat-dump.sh not owned by root (owner=\$$owner)\"; exit 1; }; \
			\
			# Permission check (BusyBox-safe): match -rw------- exactly \
			perms=\$$(ls -l /tmp/nat-dump.sh | awk \"{print \\\$1}\"); \
			[ \"\$$perms\" = \"-rw-------\" ] || { echo \"❌ nat-dump.sh permissions not 600 (perms=\$$perms)\"; exit 1; }; \
		" \
	')

	# 4) Execute explicitly (no PATH lookup)
	@$(call WITH_SECRETS, sh -c '\
		ssh -p "$$ROUTER_SSH_PORT" "$$SSH_USER_ROUTER@$$ROUTER_ADDR" "sh /tmp/nat-dump.sh" \
	')

	# 5) Ephemeral cleanup
	@$(call WITH_SECRETS, sh -c '\
		ssh -p "$$ROUTER_SSH_PORT" "$$SSH_USER_ROUTER@$$ROUTER_ADDR" "rm -f /tmp/nat-dump.sh" \
	')

	@echo "🎯 NAT pipeline complete"

