#!/bin/bash
# install-wireguard-server.sh v1.1 — Julien's reproducible WireGuard setup
# Sets up kernel-mode WireGuard on 192.168.50.4 with port 51420 and subnet 10.4.0.0/24
# Also provisions this node as client 10.4.0.4 for testing
# Assumes UGOS environment — no package updates, no Docker

set -euo pipefail
WG_CONF="/etc/wireguard/wg0.conf"
WG_INTERFACE="wg0"
WG_PORT="51420"
WG_SUBNET="10.4.0.1/24"
LAN_SUBNET="192.168.50.0/24"
LAN_INTERFACE="bridge0"
DNS_PRIMARY="192.168.50.4"
DNS_FALLBACK="192.168.50.1"

echo "🔐 Regenerating compromised server keys..."
SERVER_PRIV=$(wg genkey)
SERVER_PUB=$(echo "$SERVER_PRIV" | wg pubkey)

echo "🔐 Generating client keys for 10.4.0.4..."
CLIENT_PRIV=$(wg genkey)
CLIENT_PUB=$(echo "$CLIENT_PRIV" | wg pubkey)

echo "📝 Writing WireGuard config to $WG_CONF..."
cat > "$WG_CONF" <<EOF
# WireGuard server config — autogenerated v1.1
# Created: $(date -Iseconds)

[Interface]
Address = $WG_SUBNET
ListenPort = $WG_PORT
PrivateKey = $SERVER_PRIV
MTU = 1420

# NAT for VPN clients to reach internet via LAN
PostUp   = iptables -t nat -A POSTROUTING -s 10.4.0.0/24 -o $LAN_INTERFACE -j MASQUERADE; iptables -A FORWARD -i $WG_INTERFACE -j ACCEPT; iptables -A FORWARD -o $WG_INTERFACE -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -s 10.4.0.0/24 -o $LAN_INTERFACE -j MASQUERADE; iptables -D FORWARD -i $WG_INTERFACE -j ACCEPT; iptables -D FORWARD -o $WG_INTERFACE -j ACCEPT

# Pre-provisioned peer: this same node as client 10.4.0.4
[Peer]
PublicKey = $CLIENT_PUB
AllowedIPs = 10.4.0.4/32
EOF

chmod 600 "$WG_CONF"

echo "🚀 Starting WireGuard interface..."
wg-quick down "$WG_INTERFACE" 2>/dev/null || true
wg-quick up "$WG_INTERFACE"

echo "✅ WireGuard server is running on port $WG_PORT with subnet $WG_SUBNET"
echo "📡 Advertising LAN subnet $LAN_SUBNET"
echo "🔑 Server public key:"
echo "$SERVER_PUB"

# Generate matching client config
CLIENT_CONF="/etc/wireguard/client-10.4.0.4.conf"
cat > "$CLIENT_CONF" <<EOF
# Autogenerated client config for 10.4.0.4
[Interface]
PrivateKey = $CLIENT_PRIV
Address = 10.4.0.4/32
DNS = $DNS_PRIMARY,$DNS_FALLBACK
MTU = 1420

[Peer]
PublicKey = $SERVER_PUB
Endpoint = $(hostname -I | awk '{print $1}'):$WG_PORT
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
EOF

chmod 600 "$CLIENT_CONF"

echo "📄 Client config written to $CLIENT_CONF"
echo "📱 To onboard, scan this QR code:"
qrencode -t ansiutf8 < "$CLIENT_CONF"
