#!/usr/bin/env bash
#
# scripts/wg-compile-clients.sh
#
# Render deterministic client + server peer configs from compiled plan.tsv.
# One worker per interface (parallel-safe).
#
# Input (authoritative for rendering):
#   /volume1/homelab/wireguard/compiled/plan.tsv
#
# This script MUST be a dumb renderer:
# - no address math
# - no policy decisions
# - no AllowedIPs computation
#

set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

: "${WG_ROOT:?WG_ROOT not set}"

PLAN="${WG_ROOT}/compiled/plan.tsv"
KEYS="${WG_ROOT}/compiled/keys.tsv"

OUT_ROOT="${WG_OUT:-${WG_ROOT}/out}"
OUT_CLIENT="${OUT_ROOT}/clients"
OUT_SERVER="${OUT_ROOT}/server/peers"

KEY_WIDTH=16

mkdir -p "$OUT_CLIENT" "$OUT_SERVER"
chmod 700 "$OUT_CLIENT" "$OUT_SERVER" 2>/dev/null || true

[ -f "$PLAN" ] || { echo "ERROR: missing plan.tsv at $PLAN" >&2; exit 1; }
[ -f "$KEYS" ] || { echo "ERROR: missing keys.tsv at $KEYS" >&2; exit 1; }

# --------------------------------------------------------------------
# Validate strict TSV header
# --------------------------------------------------------------------
awk -F'\t' '
	/^#/ { next }
	/^[[:space:]]*$/ { next }
	!seen {
		seen=1
		if ($1=="base" &&
			$2=="iface" &&
			$3=="slot" &&
			$4=="dns" &&
			$5=="client_addr4" &&
			$6=="client_addr6" &&
			$7=="AllowedIPs_client" &&
			$8=="AllowedIPs_server" &&
			$9=="endpoint") exit 0
		exit 1
	}
' "$PLAN" || {
	echo "ERROR: plan.tsv header does not match strict TSV contract" >&2
	exit 1
}

compile_iface() {
	local iface="$1"
	local ifnum="${iface#wg}"

	[[ "$ifnum" =~ ^[0-9]+$ ]] || {
		echo "ERROR: invalid iface '$iface'" >&2
		exit 1
	}

	local server_pub="${WG_ROOT}/server-keys/${iface}.pub"
	[ -f "$server_pub" ] || {
		echo "ERROR: missing server public key $server_pub" >&2
		exit 1
	}

	local server_pubkey
	server_pubkey="$(tr -d '\r\n' <"$server_pub")"
	[ -n "$server_pubkey" ] || {
		echo "ERROR: empty server public key in $server_pub" >&2
		exit 1
	}


	mkdir -p "$OUT_SERVER/$iface"
	echo "rendering interface $iface"

	awk -F'\t' \
		-v KEYS="$KEYS" \
		-v IFACE="$iface" \
		-v OUTC="$OUT_CLIENT" \
		-v OUTS="$OUT_SERVER" \
		-v SERVER_PUB="$server_pubkey" \
		-v KEYW="$KEY_WIDTH" '
		function kv(file, key, val) {
			printf "%-*s = %s\n", KEYW, key, val >> file
		}

		BEGIN {
			while ((getline < KEYS) > 0) {
				if ($0 ~ /^[[:space:]]*$/) continue
				if ($1=="base" && $2=="iface") continue

				key = $1 SUBSEP $2
				if (key in priv) {
					printf "ERROR: duplicate key entry for base=%s iface=%s\n", $1, $2 > "/dev/stderr"
					exit 1
				}

				pub[key]  = $3
				priv[key] = $4
			}
			close(KEYS)
		}

		/^#/ { next }
		/^[[:space:]]*$/ { next }

		# Skip header row
		$1=="base" &&
		$2=="iface" &&
		$3=="slot" &&
		$4=="dns" &&
		$5=="client_addr4" &&
		$6=="client_addr6" &&
		$7=="AllowedIPs_client" &&
		$8=="AllowedIPs_server" &&
		$9=="endpoint" { next }

		{
			if ($2 != IFACE) next

			key = $1 SUBSEP $2
			if (!(key in priv) || !(key in pub)) {
				printf "ERROR: missing keys for base=%s iface=%s\n", $1, $2 > "/dev/stderr"
				exit 2
			}

			client_file = OUTC "/" $1 "-" $2 ".conf"
			server_file = OUTS "/" $2 "/" $1 ".conf"

			print "# " $1 "-" $2              >  client_file
			print "# Interface: " $2          >> client_file
			print "# Slot: " $3               >> client_file
			print "# Generated by wg-compile-clients.sh" >> client_file
			print ""                          >> client_file
			print "[Interface]"               >> client_file
			kv(client_file, "PrivateKey", priv[key])
			kv(client_file, "Address", $5 ", " $6)
			if ($4 != "") kv(client_file, "DNS", $4)
			print ""                          >> client_file
			print "[Peer]"                    >> client_file
			print "# Server: homelab-" $2     >> client_file
			kv(client_file, "PublicKey", SERVER_PUB)
			kv(client_file, "Endpoint", $9)
			kv(client_file, "AllowedIPs", $7)
			kv(client_file, "PersistentKeepalive", "25")
			close(client_file)

			print "# " $1 "-" $2              >  server_file
			print "# Interface: " $2          >> server_file
			print "# Slot: " $3               >> server_file
			print "# Generated by wg-compile-clients.sh" >> server_file
			print ""                          >> server_file
			print "[Peer]"                    >> server_file
			kv(server_file, "PublicKey", pub[key])
			kv(server_file, "AllowedIPs", $8)
			close(server_file)
		}
	' "$PLAN"
}

mapfile -t IFACES < <(
	awk -F'\t' '
		/^#/ { next }
		/^[[:space:]]*$/ { next }

		# Skip header row
		$1=="base" &&
		$2=="iface" &&
		$3=="slot" &&
		$4=="dns" &&
		$5=="client_addr4" &&
		$6=="client_addr6" &&
		$7=="AllowedIPs_client" &&
		$8=="AllowedIPs_server" &&
		$9=="endpoint" { next }

		{ print $2 }
	' "$PLAN" | sort -u
)

[ "${#IFACES[@]}" -gt 0 ] || {
	echo "ERROR: no interfaces found in plan.tsv" >&2
	exit 1
}

pids=()
for iface in "${IFACES[@]}"; do
	compile_iface "$iface" &
	pids+=( "$!" )
done

for pid in "${pids[@]}"; do
	wait "$pid"
done

echo "client configs written to $OUT_CLIENT"
echo "server peer fragments written to $OUT_SERVER"
