name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install all required tools
        run: make install-all

      - name: Run strict lint suite
        run: make lint-ci
